# -*- coding: utf-8 -*-


#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.consoleWidget = PythonConsoleWidget(self.centralwidget)
        self.consoleWidget.setGeometry(QtCore.QRect(180, 280, 531, 20))
        self.consoleWidget.setObjectName("consoleWidget")
        self.pyDemo = PyDemo(self.centralwidget)
        self.pyDemo.setGeometry(QtCore.QRect(190, 50, 571, 211))
        self.pyDemo.setObjectName("pyDemo")
        self.polygonWidget = PolygonWidget(self.centralwidget)
        self.polygonWidget.setGeometry(QtCore.QRect(140, 380, 120, 120))
        self.polygonWidget.setObjectName("polygonWidget")
        self.analogClock = PyAnalogClock(self.centralwidget)
        self.analogClock.setGeometry(QtCore.QRect(240, 330, 201, 161))
        self.analogClock.setObjectName("analogClock")
        self.multipagewidget = PyMultiPageWidget(self.centralwidget)
        self.multipagewidget.setGeometry(QtCore.QRect(580, 340, 200, 150))
        self.multipagewidget.setObjectName("multipagewidget")
        self.page = QtWidgets.QWidget(self.multipagewidget)
        self.page.setObjectName("page")
        self.pyDateEdit = PyDateEdit(self.centralwidget)
        self.pyDateEdit.setGeometry(QtCore.QRect(40, 310, 122, 20))
        self.pyDateEdit.setObjectName("pyDateEdit")
        self.webEngineView = QtWebEngineWidgets.QWebEngineView(self.centralwidget)
        self.webEngineView.setGeometry(QtCore.QRect(480, 120, 300, 200))
        self.webEngineView.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView.setObjectName("webEngineView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.consoleWidget.setToolTip(_translate("MainWindow", "Python console"))
        self.consoleWidget.setWhatsThis(_translate("MainWindow", "The Python console widget can be used to explore Qt Designer."))
        self.pyDemo.setToolTip(_translate("MainWindow", "PyQt demonstration widget"))
        self.pyDemo.setWhatsThis(_translate("MainWindow", "PyDemo is a demonstration custom widget written in Python using PyQt."))
        self.analogClock.setToolTip(_translate("MainWindow", "The current time"))
        self.analogClock.setWhatsThis(_translate("MainWindow", "The analog clock widget displays the current time."))
from PyQt5 import QtWebEngineWidgets
from analogclock import PyAnalogClock
from datetimeedit import PyDateEdit
from multipagewidget import PyMultiPageWidget
from polygonwidget import PolygonWidget
from pydemo import PyDemo
from pythonconsolewidget import PythonConsoleWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())    